[tool.poetry]
name = "django-rest-basic"
version = "0.1.0"
description = ""
authors = ["vicrrs"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0.4"
autopep8 = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
